_wandb:
    value:
        cli_version: 0.22.1
        e:
            7na4bj4crvrt904xv446eo11mwoser00:
                args:
                    - --n-trials
                    - "100"
                    - --wandb
                    - test_project
                    - --study-name
                    - my_study
                    - --trial-steps
                    - "40000"
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "980122034176"
                        used: "661436030976"
                email: neil.c.tan@gmail.com
                executable: /home/neil/.pyenv/versions/world/bin/python
                git:
                    commit: 014249653fa480ff8c89ed6486b3c698071ca99e
                    remote: git@github.com:robotic-ai-core/LightningTune.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-ceb02df1-c226-6eae-1805-991c1bf36ed5
                host: FirePillar
                memory:
                    total: "67323334656"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: -m pytest.__main__
                python: CPython 3.10.14
                root: /home/neil/code/modelling/ProtoWorld/external/LightningTune
                startedAt: "2025-11-25T05:23:59.772166Z"
                writerId: 7na4bj4crvrt904xv446eo11mwoser00
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 50
                - 63
                - 71
                - 83
                - 106
            "2":
                - 1
                - 11
                - 35
                - 41
                - 49
                - 50
                - 63
                - 71
                - 83
                - 106
            "3":
                - 2
            "4": 3.10.14
            "5": 0.22.1
            "6": 4.56.2
            "12": 0.22.1
            "13": linux-x86_64
