data:
  batch_size: 32
  num_samples: 1000
model:
  dropout: 0.1751232755033369
  hidden_size: 48
  learning_rate: 0.0030821179762349294
  optimizer_type: adam
trainer:
  enable_checkpointing: false
  enable_progress_bar: false
  logger: false
  max_epochs: 5
