data:
  batch_size: 32
  num_samples: 1000
model:
  dropout: 0.08269000917321562
  hidden_size: 128
  learning_rate: 0.0003206056705947809
  optimizer_type: rmsprop
trainer:
  enable_checkpointing: false
  enable_progress_bar: false
  logger: false
  max_epochs: 5
